name: List Github models
on:
  workflow_dispatch:
    inputs:
      llm:
        description: 'LLM connection'
        required: false
        type: choice
        options:
          - '{"model": "github:openai/gpt-4.1", "provider": "github"}'
          - '{"model": "anthropic_bedrock:arn:aws:bedrock:us-east-1:024871859028:inference-profile/us.anthropic.claude-sonnet-4-20250514-v1:0", "provider": "anthropic_bedrock"}'

jobs:
  list:
    runs-on: ubuntu-latest
    permissions:
      models: read
      id-token: write   # required for OIDC
      contents: read
    steps:
      - name: Call GitHub Models catalog
        run: |
          curl -L \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://models.github.ai/catalog/models | jq .

      - name: Clone repo
        uses: actions/checkout@v4
        with:
            ## All history for git diff below to succeed.
            fetch-depth: 0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::024871859028:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Run Hello World to check authentication and authorization.
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEBUG=* npx --yes genaiscript@latest run --provider $(echo '${{ github.event.inputs.llm }}' | jq -r .provider) --model $(echo '${{ github.event.inputs.llm }}' | jq -r .model) genaisrc/HelloWorld.genai.mts

      ## Postprocess the TLAi benchmarks
      ##

      - run: cat .genaiscript/runs/HelloWorld/*/trace.md
        if: always()

      - name: Archive generated TLA+ specs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: ListModels
          path: |
            .genaiscript/*
